version: "3.8"

volumes:
  data-volume: { }

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'exercise'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'adminadmin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data-volume:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:rw

  encryption:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
    depends_on:
      - db
    links:
      - db