version: "3.8"

volumes:
  data-volume: { }

services:
  mysql-exercise:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      #MYSQL_ROOT_PASSWORD: 'adminadmin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data-volume:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql:rw

  encryption:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
    expose:
      - '8097'
    depends_on:
      - mysql-exercise
    links:
      - mysql-exercise:db